name: stagexl_toolkit
version: 0.1.2
author: Bernhard Pichler <support@stagexl.org>
description: The 'Toolkit for Dart' runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Toolkit

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.0'