name: stagexl_toolkit
version: 0.1.0
author: Bernhard Pichler <support@stagexl.org>
description: The 'Toolkit for Dart' runtime for the StageXL library.
homepage: https://github.com/bp74/StageXL_Toolkit
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: any
  stagexl: '>=0.13.3 <0.14.0'
transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives"]
    minify: true
